### ISSUE TITLE
October 1st, 2020, Amazon SES will only support requests signed using Signature Version 4

### ISSUE THREAD

**Issue by Alexander-Pop** [francescogabbrielli/SwiftAwsSesTransport#1]
any plans to be ready for this: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html
TY

**Comment by francescogabbrielli** [comment]
Hi Alex, sorry I did not see this.

This library is actually using AWS SDK in the background, so it should already be compliant with version 4.

I can share a sample if you need

**Comment by Alexander-Pop** [comment]
Yes please

**Comment by francescogabbrielli** [comment]
Ok Alex, I needed to reinstall all my PHP environment... it has been a while not working on this. I notice there is a problem with namespaces so it actually won't autoload the classes. 

But, after fully configuring SES on your console, just using my [wrapper](https://github.com/francescogabbrielli/AwsSesWrapper) you can do:

```php
require './vendor/autoload.php';

AwsSesWrapper\AwsSesWrapper::factory('eu-central-1', 'default', 'TestConfigSet')
	->setDebug(true)
	->setFrom('demo@your_verified_email.com')
	->sendEmail(['to'=>['a_reachable_one@mail.com']], 'Test E-mail from SDK', 'HTML', 'Text')
```

Also you have `sendRawEmail`, `sendTemplatedEmail`, `sendBulkTemplatedEmail` (which BTW is the most useful thing in this whole work). Hope this helps

**Comment by Alexander-Pop** [comment]
TY bro
